# Generated by Django 3.1.5 on 2021-02-19 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(editable=False)),
                ('timestamp_changed', models.DateTimeField(editable=False)),
                ('id_slug', models.CharField(editable=False, max_length=18, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField(blank=True, null=True)),
                ('order_num', models.IntegerField(default=0, editable=False)),
                ('book', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='knowledge.book')),
                ('created_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
