# Generated by Django 3.1.5 on 2021-02-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order_num']},
        ),
    ]
