# Generated by Django 3.1.5 on 2021-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20210220_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='source',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
