# Generated by Django 3.1.5 on 2021-02-28 19:31

from django.db import migrations, models
import django.db.models.deletion
import knowledge.models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_auto_20210224_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(editable=False, limit_choices_to=knowledge.models.Chapter.get_choices, on_delete=django.db.models.deletion.CASCADE, to='knowledge.book'),
        ),
    ]
