# Generated by Django 3.1.5 on 2021-01-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210123_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_deleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
