# Generated by Django 3.1.5 on 2021-01-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestamp_confirmation_code_send',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
