# Generated by Django 3.1.5 on 2021-01-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_timestamp_confirmation_code_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_you',
            field=models.TextField(blank=True, null=True),
        ),
    ]
