# Generated by Django 3.1.5 on 2021-02-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210212_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionregister',
            options={'default_permissions': (), 'managed': False, 'permissions': (('landingpage_right', 'Right to view landingpage'), ('health_app', 'Right to user Health App'), ('personality_app', 'Use Personality App'), ('habit_app', 'Right to use Habit App'), ('knowledge_app', 'Right to use Knowledge App'))},
        ),
    ]
