# Generated by Django 3.1.5 on 2021-02-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalityprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='profile_about',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='timestamp_changed',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='timestamp_created',
            field=models.DateTimeField(editable=False),
        ),
        migrations.CreateModel(
            name='PersonalityNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(editable=False)),
                ('timestamp_changed', models.DateTimeField(editable=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('sphere', models.IntegerField(choices=[(1, 'Arbeit'), (2, 'Finanzen'), (3, 'Gesundheit'), (4, 'Freizeit'), (5, 'Beziehungen'), (6, 'Familie'), (7, 'Geselligkeit'), (8, 'Persönlichkeit')], default=8)),
                ('id_slug', models.CharField(editable=False, max_length=18, unique=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('note_about', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
