# Generated by Django 3.1.5 on 2021-02-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0003_auto_20210213_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitynote',
            name='sphere',
            field=models.IntegerField(choices=[(1, 'Arbeit'), (2, 'Finanzen'), (3, 'Gesundheit'), (4, 'Freizeit'), (5, 'Beziehung'), (6, 'Familie'), (7, 'Geselligkeit'), (8, 'Persönlichkeit')], default=8),
        ),
    ]
