# Generated by Django 3.1.5 on 2021-02-20 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(editable=False)),
                ('timestamp_changed', models.DateTimeField(editable=False)),
                ('vision_1', models.TextField(blank=True, null=True)),
                ('vision_2', models.TextField(blank=True, null=True)),
                ('vision_3', models.TextField(blank=True, null=True)),
                ('vision_4', models.TextField(blank=True, null=True)),
                ('vision_5', models.TextField(blank=True, null=True)),
                ('vision_6', models.TextField(blank=True, null=True)),
                ('vision_7', models.TextField(blank=True, null=True)),
                ('vision_8', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
