# Generated by Django 3.1.5 on 2021-02-28 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import habit.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habit', '0003_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(editable=False)),
                ('timestamp_changed', models.DateTimeField(editable=False)),
                ('id_slug', models.CharField(editable=False, max_length=18, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, null=True)),
                ('sphere', models.IntegerField(choices=[(1, 'Arbeit'), (2, 'Finanzen'), (3, 'Gesundheit'), (4, 'Freizeit'), (5, 'Beziehung'), (6, 'Familie'), (7, 'Geselligkeit'), (8, 'Persönlichkeit')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_good_habit', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('interval', models.IntegerField(choices=[(1, 'täglich'), (2, 'wöchentlich'), (3, 'monatlich')], default=1)),
                ('skip_weekend', models.BooleanField(default=False)),
                ('skip_weekdays', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Montag'), (2, 'Dienstag'), (3, 'Mittwoch'), (4, 'Donnerstag'), (5, 'Freitag'), (6, 'Samstag'), (7, 'Sonntag')], default=1)),
                ('day_of_month', models.IntegerField(choices=[(1, 'Erster Tag'), (2, 'Zweiter Tag'), (3, 'Dritter Tag'), (15, 'Monatsmitte (15.)'), (-3, 'Letzter Sonntag im Monat'), (-2, 'Vorletzter Tag'), (-1, 'Letzter Tag')], default=1)),
                ('current_streak', models.IntegerField(default=0, editable=False)),
                ('highest_streak', models.IntegerField(default=0, editable=False)),
                ('total_done', models.IntegerField(default=0, editable=False)),
                ('total_failed', models.IntegerField(default=0, editable=False)),
                ('total_canceled', models.IntegerField(default=0, editable=False)),
                ('total_counter', models.IntegerField(default=0, editable=False)),
                ('last_day', models.DateField(blank=True, editable=False, null=True)),
                ('last_day_action', models.IntegerField(blank=True, choices=[(1, 'done'), (2, 'failed'), (3, 'canceled')], editable=False, null=True)),
                ('privacy', models.IntegerField(choices=[(1, 'Nur ich'), (2, 'Meine Kontakte'), (3, 'Jeder'), (4, 'Öffentlich')], default=1)),
                ('created_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, limit_choices_to=habit.models.Habit.get_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.goal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HabitEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(editable=False)),
                ('timestamp_changed', models.DateTimeField(editable=False)),
                ('id_slug', models.CharField(editable=False, max_length=18, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('sphere', models.IntegerField(choices=[(1, 'Arbeit'), (2, 'Finanzen'), (3, 'Gesundheit'), (4, 'Freizeit'), (5, 'Beziehung'), (6, 'Familie'), (7, 'Geselligkeit'), (8, 'Persönlichkeit')])),
                ('status', models.IntegerField(choices=[(1, 'done'), (2, 'failed'), (3, 'canceled')])),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.habit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
