# Generated by Django 3.1.5 on 2021-02-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weight',
            name='timestamp_changed',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='weight',
            name='timestamp_created',
            field=models.DateTimeField(editable=False),
        ),
    ]
